Practica 1: David Israel Pérez Montes
schiob/os2sistemas pull request #7
Opened 2018-02-03 02:46 UTC by DavidDark

2018-02-04 01:10 UTC, schiob commented on ene-jun-2018/prácticas/DavidIsraelPerezMontes/práctica1/practica1.go
> +package main
Este archivo está en la carpeta de prácticas, elimínalo

2018-02-04 01:10 UTC, schiob commented on ene-jun-2018/David Israel Perez Montes/práctica1/practica1.go
> +    text, _ := reader.ReadString('\n')
No tuviste problemas al leer con este método?

2018-02-04 01:10 UTC, schiob commented on ene-jun-2018/David Israel Perez Montes/práctica1/practica1.go
> +		go hello(i)
Por qué usaste `i` acá? Para meter algo de aleatoriedad?

2018-02-04 03:07 UTC, DavidDark commented on ene-jun-2018/David Israel Perez Montes/práctica1/practica1.go
> +    text, _ := reader.ReadString('\n')
Solo que me forzaba a poner el carácter entre los paréntesis, "('\n')", para terminar la línea de escritura

2018-02-04 03:08 UTC, DavidDark commented on ene-jun-2018/David Israel Perez Montes/práctica1/practica1.go
> +		go hello(i)
De hecho, para repetir 10 veces cada método

2018-02-04 03:11 UTC, DavidDark commented on ene-jun-2018/prácticas/DavidIsraelPerezMontes/práctica1/practica1.go
> +package main
Es que hice dos "push origin master", con el segundo corregí la ubicación cambiando al archivo de lugar, ¿tengo que borrarlo como quiera?

2018-02-04 03:54 UTC, schiob commented on ene-jun-2018/prácticas/DavidIsraelPerezMontes/práctica1/practica1.go
> +package main
Sip, porque con el primero parece que comoquiera sigue en esta ruta

2018-02-04 03:56 UTC, schiob commented on ene-jun-2018/David Israel Perez Montes/práctica1/practica1.go
> +		go hello(i)
Pero adentro de la función solo lo usas para el sleep

2018-02-23 01:44 UTC, schiob requested changes

2018-02-23 01:44 UTC, schiob commented on ene-jun-2018/David Israel Perez Montes/Practica2/practica2.go
> +		fmt.Println("Numero de caracteres: ", len(body))
Está bien, pero el número de caracteres lo estás imprimiendo a pantalla, y no lo regresas en el response, solo le estás escribiendo lo de la línea 40

2018-02-23 01:44 UTC, schiob commented on ene-jun-2018/prácticas/DavidIsraelPerezMontes/práctica1/practica1.go
> +package main
Todavía tienes este archivo en la carpeta de prácticas xD, bórralo porfa :)

2018-06-01 19:06 UTC, merged