Practica2/ClaudiaSaldivar/Revisar
schiob/os2sistemas pull request #9
Opened 2018-02-24 18:55 UTC by claudiasaldivar

2018-02-25 01:01 UTC, schiob requested changes
Chécate de dónde lees el texto :smile:

2018-02-25 01:01 UTC, schiob commented on ene-jun-2018/claudia_saldivar/practica2/main.go
> +  fmt.Scanf("%v", &texto)
Este Scanf toma la entrada de la entrada estandar, y tú tienes que leerla de la Request. Checate el campo de Body de [Request](https://golang.org/pkg/net/http/#Request)

2018-02-25 01:02 UTC, schiob commented on ene-jun-2018/claudia_saldivar/practica2/main.go
> +  fmt.Scanf("%v", &texto)
Todo lo demás se ve que funciona

2018-03-04 21:57 UTC, claudiasaldivar commented
Solo falta en el servidor que me muestre el contenido en el localhost, no se en que parte hacer los cambios :(

2018-03-05 21:50 UTC, schiob reviewed
Lo agregaste en lo de la primera parte. Y recuerda correr go fmt para que el código se vea bonito (Y sea más fácil leerlo xD)

2018-03-05 21:50 UTC, schiob commented on ene-jun-2018/claudia_saldivar/practica2/main.go
> +	scanner := bufio.NewScanner(os.Stdin)
Supongo que este archivo es para la primera parte, en ese caso en lugar de leer de la terminal, lo tiene que sacar de r.Body, que es el contenido del Request

2018-03-05 21:50 UTC, schiob commented on ene-jun-2018/claudia_saldivar/practica2/chat.go
> +                // echoing the message back out
Por acá es donde deberías de poner la lectura de STDIN para regresarle eso en lugar de el echo

2018-03-16 18:45 UTC, schiob reviewed
No entendí para que ibas a usar el runtime os u.u

2018-03-16 18:46 UTC, merged